trackList = 
[
{name:"0001. Bad Guy壞女人 ",artist:"Billie Eilish ",src:"music/Billie Eilish - Bad Guy壞女人中文字幕 Lyrics.mp3"},
{name:"0002. 宇宙最強神團 LSD 神曲 Audio (中字MV)",artist:" LSD ",src:"music/宇宙最強神團 LSD 神曲 Audio (中字MV).mp3"},
{name:"0003. Ariana Grande - Side to Side",artist:"Ariana Grande ",src:"music/Ariana Grande - Side to Side - Sexy Bike Riding Version.mp3"},
{name:"0004. Avril Lavigne - When Youre Gone",artist:"Avril Lavigne ",src:"music/Avril Lavigne - When Youre Gone (Officia Music Video).mp3"},
{name:"0005. Avril Lavigne 艾薇兒 . Complicated 複雜 中文字幕",artist:"Avril Lavigne 艾薇兒 ",src:"music/Avril Lavigne 艾薇兒 . Complicated 複雜 中文字幕.mp3"},
{name:"0006. Avril Lavigne 艾薇兒 . Head Above Water 不再沉淪 ",artist:"Avril Lavigne 艾薇兒 ",src:"music/Avril Lavigne 艾薇兒 . Head Above Water 不再沉淪 中文字幕(TaiwaneseChinese Sub).mp3"},
{name:"0007. Beauty And A Beat - Justin Bieber (Alex Goot, Kurt Schneider, and Chrissy Costanza Cover)",artist:"Alex Goot, Kurt Schneider, and Chrissy Costanza Cover ",src:"music/Beauty And A Beat - Justin Bieber (Alex Goot, Kurt Schneider, and Chrissy Costanza Cover).mp3"},
{name:"0008. Clean Bandit - Mama (feat. Ellie Goulding) [Official Video]",artist:"Clean Bandit ",src:"music/Clean Bandit - Mama (feat. Ellie Goulding) [Official Video].mp3"},
{name:"0009. Clean Bandit - Solo (feat. Demi Lovato) [Official Video]",artist:"Clean Bandit ",src:"music/Clean Bandit - Solo (feat. Demi Lovato) [Official Video].mp3"},
{name:"0010. Clean Bandit - Symphony (feat. Zara Larsson) [Official Video]",artist:"Clean Bandit ",src:"music/Clean Bandit - Symphony (feat. Zara Larsson) [Official Video].mp3"},
{name:"0011. Counting Stars - One Republic - w Chrissy Alex Goot",artist:"Counting Stars ",src:"music/Counting Stars - One Republic - w Chrissy Alex Goot.mp3"},
{name:"0012. Crazy Frog - Axel F (Official Video)",artist:"Crazy Frog ",src:"music/Crazy Frog - Axel F (Official Video).mp3"},
{name:"0013. Luis Fonsi - Despacito ft. Daddy Yankee",artist:"Luis Fonsi ",src:"music/Luis Fonsi - Despacito ft. Daddy Yankee.mp3"},
{name:"0014. PSY - ‘New Face’ MV",artist:"PSY ",src:"music/PSY - ‘New Face’ MV.mp3"},
{name:"0015. PSY - DADDY(feat. CL of 2NE1) MV",artist:"PSY ",src:"music/PSY - DADDY(feat. CL of 2NE1) MV.mp3"},
{name:"0016. Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song)",artist:"Shakira ",src:"music/Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song).mp3"},
{name:"0017. TONES AND I - DANCE MONKEY (OFFICIAL VIDEO)",artist:"TONES AND I  ",src:"music/TONES AND I - DANCE MONKEY (OFFICIAL VIDEO).mp3"},
{name:"0018. 宇宙最強神團 LSD 神曲 Audio (中字MV)",artist:"宇宙最強神團 LSD ",src:"music/宇宙最強神團 LSD 神曲 Audio (中字MV).mp3"},
{name:"0019. 老菸槍雙人組 The Chainsmokers ft. Halsey 海爾希 - 靠近我 Closer 中文字幕 MV",artist:"老菸槍雙人組 The Chainsmokers ",src:"music/老菸槍雙人組 The Chainsmokers ft. Halsey 海爾希 - 靠近我 Closer 中文字幕 MV.mp3"},
{name:"0020. 老菸槍雙人組 The Chainsmokers 期盼 Hope (中字MV)",artist:"老菸槍雙人組 ",src:"music/老菸槍雙人組 The Chainsmokers 期盼 Hope (中字MV).mp3"},
{name:"0021. 老菸槍雙人組與碧碧蕾克莎 The Chainsmokers Bebe Rexha 你是我的 Call You Mine (中字MV)",artist:"老菸槍雙人組 ",src:"music/老菸槍雙人組與碧碧蕾克莎 The Chainsmokers Bebe Rexha 你是我的 Call You Mine (中字MV).mp3"},
{name:"0022. Something Just Like This 如此而已 - The Chainsmokers Coldplay ",artist:"Something Just Like This ",src:"music/拯救了整座城市，卻救不了你：Something Just Like This 如此而已 - The Chainsmokers Coldplay 剪輯版 蜘蛛人驚奇再起 中文字幕.mp3"},
{name:"0023. 馬汀蓋瑞克斯 Martin Garrix 與 Bebe Rexha 以愛之名 In The Name Of Love (HD中字MV)",artist:"馬汀蓋瑞克斯 Martin Garrix ",src:"music/馬汀蓋瑞克斯 Martin Garrix 與 Bebe Rexha 以愛之名 In The Name Of Love (HD中字MV).mp3"},
{name:"0024. Q Park - AY AY AY (Official Music Video)",artist:"Q Park ",src:"music/Q Park - AY AY AY (Official Music Video).mp3"},
{name:"0025. Ava Max - So Am I [Official Music Video]",artist:"Ava Max ",src:"music/Ava Max - So Am I [Official Music Video].mp3"},
{name:"0026. Avril Lavigne - What The Hell (Official Music Video)",artist:"Avril Lavigne ",src:"music/Avril Lavigne - What The Hell (Official Music Video).mp3"},
{name:"0027. Avril Lavigne - Girlfriend (Official Music Video)",artist:"Avril Lavigne ",src:"music/Avril Lavigne - Girlfriend (Official Music Video).mp3"},
{name:"0028. 珍妮佛洛佩茲與馬盧瑪 Jennifer Lopez Maluma 只為你 Pa Ti (中字MV)",artist:"珍妮佛洛佩茲與馬盧瑪 ",src:"music/珍妮佛洛佩茲與馬盧瑪 Jennifer Lopez Maluma 只為你 Pa Ti (中字MV).mp3"},
{name:"0029. 黑眼豆豆與夏奇拉 Black Eyed Peas   Shakira 像我這樣的女孩 Girl Like Me (中字MV)",artist:"黑眼豆豆與夏奇拉 ",src:"music/黑眼豆豆與夏奇拉 Black Eyed Peas   Shakira 像我這樣的女孩 Girl Like Me (中字MV).mp3"},
{name:"0030. Maroon 5 - Animals (Lyrics)",artist:"Maroon 5 ",src:"music/Maroon 5 - Animals (Lyrics).mp3"},
{name:"0031. Clean Bandit 清潔的盜賊 - Rockabye 乖乖睡 feat. Sean Paul 尚保羅 Anne-Marie 安瑪莉 (華納 Official 高畫質 HD 官方完整版 MV)",artist:"Clean Bandit 清潔的盜賊  ",src:"music/Clean Bandit 清潔的盜賊 - Rockabye 乖乖睡 feat. Sean Paul 尚保羅 Anne-Marie 安瑪莉 (華納 Official 高畫質 HD 官方完整版 MV).mp3"},
{name:"0032. 老菸槍雙人組 The Chainsmokers 帶走愛 Takeaway (中字MV)",artist:"老菸槍雙人組 ",src:"music/老菸槍雙人組 The Chainsmokers 帶走愛 Takeaway (中字MV).mp3"},
{name:"0033. Ed Sheeran - Shape of You [Official Video]",artist:"Ed Sheeran ",src:"music/Ed Sheeran - Shape of You [Official Video].mp3"},
{name:"0034. Maroon 5 - Sugar (Lyrics)",artist:"馬輪壞 ",src:"music/Maroon 5 - Sugar (Lyrics).mp3"},
{name:"0035. Maroon 5 - Maps (Lyric Video)",artist:"馬輪壞 ",src:"music/Maroon 5 - Maps (Lyric Video).mp3"},
{name:"0036. PSY - GENTLEMAN MV",artist:"PSY ",src:"music/PSY - GENTLEMAN MV.mp3"},
{name:"0037. [Official Video] The Writers 寫手《灼火》 網路影集Mr.Bartender第三季片尾曲",artist:"Mr.Bartender ",src:"music/[Official Video] The Writers 寫手《灼火》 網路影集Mr.Bartender第三季片尾曲.mp3"},
{name:"0038. [Official Video] The Writers 寫手-剪一段我",artist:"寫手 ",src:"music/[Official Video] The Writers 寫手-剪一段我.mp3"},
{name:"0039. [音樂] 我管你 華晨宇",artist:"華晨宇 ",src:"music/[音樂] 我管你 華晨宇.mp3"},
{name:"0040. Ava Max - OMG Whats Happening [Official Music Video]",artist:"Ava Max ",src:"music/Ava Max - OMG Whats Happening [Official Music Video].mp3"},
{name:"0041. Charlie Puth - Attention [Official Video]",artist:"Charlie Puth ",src:"music/Charlie Puth - Attention [Official Video].mp3"},
{name:"0042. Clean Bandit and Mabel - Tick Tock (feat. 24kGoldn) [Official Video]",artist:"Clean Bandit ",src:"music/Clean Bandit and Mabel - Tick Tock (feat. 24kGoldn) [Official Video].mp3"},
{name:"0043. Clean Bandit 清潔的盜賊 - Mama feat. Ellie Goulding 艾麗高登 (華納 official HD 官方完整版 MV)",artist:"Clean Bandit ",src:"Clean Bandit 清潔的盜賊 - Mama feat. Ellie Goulding 艾麗高登 (華納 official HD 官方完整版 MV).mp3"},
{name:"0044. Diana Wang (王詩安) - HOME (Official Music Video)",artist:"王詩安 ",src:"music/Diana Wang (王詩安) - HOME (Official Music Video).mp3"},
{name:"0045. G.E.M.【來自天堂的魔鬼 AWAY】Official MV [HD] 鄧紫棋",artist:"鄧紫棋 ",src:"music/G.E.M.【來自天堂的魔鬼 AWAY】Official MV [HD] 鄧紫棋.mp3"},
{name:"0046. G.E.M.鄧紫棋【摩天動物園 City Zoo】Official Music Video",artist:"鄧紫棋 ",src:"music/G.E.M.鄧紫棋【摩天動物園 City Zoo】Official Music Video.mp3"},
{name:"0047. G.E.M-光年之外 LIGHT YEARS AWAY ",artist:"鄧紫棋",src:"music/G.E.M-光年之外 LIGHT YEARS AWAY .mp3"},
{name:"0048. G22 -【 蜜汁沼澤 】Official Music Video ( 韓力峻 KK 高爾宣 OSN 丁瑋 BT )",artist:"G22 ",src:"music/G22 -【 蜜汁沼澤 】Official Music Video ( 韓力峻 KK 高爾宣 OSN 丁瑋 BT ).mp3"},
{name:"0049. Jay Chou 周杰倫【稻香 Rice Field】-Official Music Video",artist:"周杰倫 ",src:"Jay Chou 周杰倫【稻香 Rice Field】-Official Music Video.mp3"},
{name:"0050. Mayday五月天[傷心的人別聽慢歌(貫徹快樂)]MV官方完整版-諾亞方舟3D電影主題曲",artist:"五月天 ",src:"music/Mayday五月天[傷心的人別聽慢歌(貫徹快樂)]MV官方完整版-諾亞方舟3D電影主題曲.mp3"},
{name:"0051. Mi2 - 勇敢愛",artist:"Mi2 ",src:"music/Mi2 - 勇敢愛.mp3"},
{name:"0052. Naughty Boy - La la la ft. Sam Smith (Official Video)",artist:"Naughty Boy ",src:"music/Naughty Boy - La la la ft. Sam Smith (Official Video).mp3"},
{name:"0053. Pharrell Williams - Happy (Official Music Video)",artist:"Pharrell Williams ",src:"music/Pharrell Williams - Happy (Official Music Video).mp3"},
{name:"0054. Rosie楊凱琳余楓《怎麼還不愛 Why Not Love》Official Music Video",artist:"楊凱琳余楓 ",src:"music/Rosie楊凱琳余楓《怎麼還不愛 Why Not Love》Official Music Video.mp3"},
{name:"0055. Shakira - Try Everything 全力以赴 中英文歌詞",artist:"Shakira ",src:"music/Shakira - Try Everything 全力以赴 中英文歌詞.mp3"},
{name:"0056. Shawn Mendes - Theres Nothing Holdin Me Back",artist:"Shawn Mendes ",src:"music/Shawn Mendes - Theres Nothing Holdin Me Back.mp3"},
{name:"0057. Shawn Mendes - Treat You Better",artist:"Shawn Mendes ",src:"music/Shawn Mendes - Treat You Better.mp3"},
{name:"0058. The Writers 寫手 [ BURN ]-網路影集《私室》主題曲",artist:"寫手 ",src:"music/The Writers 寫手 [ BURN ]-網路影集《私室》主題曲.mp3"},
{name:"0059. The Writers 寫手 《To My World》- Mr.Bartender主題曲",artist:"寫手 ",src:"music/The Writers 寫手 《To My World》- Mr.Bartender主題曲.mp3"},
{name:"0060. The Writers 寫手-自由歌",artist:"寫手 ",src:"music/The Writers 寫手-自由歌.mp3"},
{name:"0061. Tokyo Bon 東京盆踊り2020 (MakuDonarudo) Namewee 黃明志 ",artist:"黃明志 ",src:"music/Tokyo Bon 東京盆踊り2020 (MakuDonarudo) Namewee 黃明志 .mp3"},
{name:"0062. UNDER LOVER - 癡情玫瑰花 ft 玖壹壹 春風 (官方Music video)",artist:"UNDER LOVER ",src:"music/UNDER LOVER - 癡情玫瑰花 ft 玖壹壹 春風 (官方Music video).mp3"},
{name:"0063. VAVA - 我的新衣 My New Swag (Feat. Ty. 王倩倩) (華納 Official HD 官方MV)",artist:"VAVA ",src:"music/VAVA - 我的新衣 My New Swag (Feat. Ty. 王倩倩) (華納 Official HD 官方MV).mp3"},
{name:"0064. 九九Sophie Chen陳忻玥Vicky Chen-【Fall in love】歌詞Lyrics",artist:"陳忻玥 ",src:"music/九九Sophie Chen陳忻玥Vicky Chen-【Fall in love】歌詞Lyrics.mp3"},
{name:"0065. 八三夭831 【來互相傷害】feat. A-Lin Official Music Video",artist:"831 ",src:"music/八三夭831 【來互相傷害】feat. A-Lin Official Music Video.mp3"},
{name:"0066. 八三夭831 feat. 玖壹壹【馬子狗】反骨男孩酷炫執導 Official Music Video",artist:"831 ",src:"music/八三夭831 feat. 玖壹壹【馬子狗】反骨男孩酷炫執導 Official Music Video.mp3"},
{name:"0067. 八三夭831【致青春 Young Guns】Official Music Video",artist:"831 ",src:"music/八三夭831【致青春 Young Guns】Official Music Video.mp3"},
{name:"0068. 刀马旦-李玟、邓紫棋 ",artist:"李玟 ",src:"music/刀马旦-李玟、邓紫棋 .mp3"},
{name:"0069. 卜學亮(阿亮)【超跑情人夢】官方MV (Official Music Video)",artist:"卜學亮 ",src:"music/卜學亮(阿亮)【超跑情人夢】官方MV (Official Music Video).mp3"},
{name:"0070. 王心凌 Cyndi Wang – 劈你的雷正在路上 (Official Music Video)",artist:"王心凌 Cyndi Wang ",src:"music/王心凌 Cyndi Wang – 劈你的雷正在路上 (Official Music Video).mp3"},
{name:"0071. 不僅僅是喜歡 - 孫語賽、蕭全「我要你留戀我在你身旁，愛我像我愛你一樣」動態歌詞版",artist:"孫語賽 ",src:"music/不僅僅是喜歡 - 孫語賽、蕭全「我要你留戀我在你身旁，愛我像我愛你一樣」動態歌詞版.mp3"},
{name:"0072. 王心凌 Cyndi Wang《在青春迷失的咖啡館》Official Music Video",artist:"王心凌 ",src:"music/王心凌 Cyndi Wang《在青春迷失的咖啡館》Official Music Video.mp3"},
{name:"0073. 永彬Ryan.B - 放個大招給你看 ‖完整版【動態歌詞Lyrics】",artist:"永彬Ryan.B ",src:"music/永彬Ryan.B - 放個大招給你看 ‖完整版【動態歌詞Lyrics】.mp3"},
{name:"0074. 华晨宇 - 烟火里的尘埃 ",artist:"华晨宇 ",src:"music/华晨宇 - 烟火里的尘埃 .mp3"},
{name:"0075. 华晨宇《我很丑可是我很温柔》",artist:"华晨宇 ",src:"music/华晨宇《我很丑可是我很温柔》.mp3"},
{name:"0076. 囝仔(草屯囝仔臭屁嬰仔)【扛壩子 Big Boss】Official Music Video",artist:"草屯囝仔臭屁嬰仔 ",src:"music/囝仔(草屯囝仔臭屁嬰仔)【扛壩子 Big Boss】Official Music Video.mp3"},
{name:"0077. 朴樹 - 平凡之路 [歌詞字幕][電影《後會無期》主題曲][完整高清音質] The Continent Theme Song - The Ordinary Road (Pu Shu)",artist:"朴樹 ",src:"music/朴樹 - 平凡之路 [歌詞字幕][電影《後會無期》主題曲][完整高清音質] The Continent Theme Song - The Ordinary Road (Pu Shu).mp3"},
{name:"0078. 老菸槍雙人組 The Chainsmokers 厭世男孩 Sick Boy (HD中字MV)",artist:"老菸槍雙人組 ",src:"music/老菸槍雙人組 The Chainsmokers 厭世男孩 Sick Boy (HD中字MV).mp3"},
{name:"0079. 我命不由天",artist:"無 ",src:"music/我命不由天.mp3"},
{name:"0080. 李杰明 W.M.L -【你接受嗎 feat. 陳忻玥 Vicky Chen】Can You Accept Official MV",artist:"李杰明  ",src:"music/李杰明 W.M.L -【你接受嗎 feat. 陳忻玥 Vicky Chen】Can You Accept Official MV.mp3"},
{name:"0081. 李杰明 W.M.L -【沒有回頭路 No Turning Back】feat. 庭竹｜Official MV",artist:"李杰明 ",src:"music/李杰明 W.M.L -【沒有回頭路 No Turning Back】feat. 庭竹｜Official MV.mp3"},
{name:"0082. 李毓芬Tia Lee《是我不夠好Not Good Enough》Official Music Video HD",artist:"李毓芬 ",src:"music/李毓芬Tia Lee《是我不夠好Not Good Enough》Official Music Video HD.mp3"},
{name:"0083. 李榮浩 Ronghao Li - 年少有為 If I Were Young (華納 Official HD 官方MV)",artist:"李榮浩 ",src:"music/李榮浩 Ronghao Li - 年少有為 If I Were Young (華納 Official HD 官方MV).mp3"},
{name:"0084. 李榮浩 - 等著等著就老了",artist:"李榮浩 ",src:"music/0084. 李榮浩 - 等著等著就老了.mp3"},
{name:"0085. 汪蘇瀧 - 一笑傾城《微微一笑很傾城片頭曲》【動態歌詞Lyrics】",artist:"汪蘇瀧 ",src:"music/汪蘇瀧 - 一笑傾城《微微一笑很傾城片頭曲》【動態歌詞Lyrics】.mp3"},
{name:"0086. 玖壹壹(Nine one one) - 大家樂 _Ft_. _阿聖 Everybody Happy Ft. Shen 官方MV首播",artist:"911 ",src:"music/玖壹壹(Nine one one) - 大家樂 _Ft_. _阿聖 Everybody Happy Ft. Shen 官方MV首播.mp3"},
{name:"0087. 玖壹壹(Nine one one) - 男子漢的浪漫 Men’s Romance 官方MV首播",artist:"911 ",src:"music/玖壹壹(Nine one one) - 男子漢的浪漫 Men’s Romance 官方MV首播.mp3"},
{name:"0088. 玖壹壹(Nine one one)-下輩子 官方MV首播",artist:"911 ",src:"music/玖壹壹(Nine one one)-下輩子 官方MV首播.mp3"},
{name:"0089. 玖壹壹（Nine one one)回來我身邊 官方MV首播",artist:"911 ",src:"music/玖壹壹（Nine one one)回來我身邊 官方MV首播.mp3"},
{name:"0090. 玖壹壹(Nine one one)-明天再擱來 (官方MV首播)",artist:"911 ",src:"music/玖壹壹(Nine one one)-明天再擱來 (官方MV首播).mp3"},
{name:"0091. 玖壹壹(Nine one one)-歪國人「Foreigner」 (官方MV首播)",artist:"911 ",src:"music/玖壹壹(Nine one one)-歪國人「Foreigner」 (官方MV首播).mp3"},
{name:"0092. 玖壹壹(Nine one one)-嫁給我吧 官方MV首播",artist:"911 ",src:"music/玖壹壹(Nine one one)-嫁給我吧 官方MV首播.mp3"},
{name:"0093. 玖壹壹(Nine one one)-嘻哈庄腳情 官方MV首播",artist:"911 ",src:"music/玖壹壹(Nine one one)-嘻哈庄腳情 官方MV首播.mp3"},
{name:"0094. 玖壹壹(洋蔥)-癡情的男子漢 ft UnderLover(睿兒)",artist:"911 ",src:"music/玖壹壹(洋蔥)-癡情的男子漢 ft UnderLover(睿兒).mp3"},
{name:"0095. 辛巴巴巴噜比啦",artist:"抖音 ",src:"music/辛巴巴巴噜比啦.mp3"},
{name:"0096. 周杰倫 Jay Chou (特別演出 派偉俊)【告白氣球 Love Confession】Official MV",artist:"周杰倫 ",src:"music/周杰倫 Jay Chou (特別演出 派偉俊)【告白氣球 Love Confession】Official MV.mp3"},
{name:"0097. 周杰倫 Jay Chou-Mojito",artist:"周杰倫 ",src:"music/周杰倫 Jay Chou-Mojito.mp3"},
{name:"0098. 周湯豪 -角頭 電影主題曲",artist:"周湯豪 ",src:"music/周湯豪 -角頭 電影主題曲.mp3"},
{name:"0099. 東城衛x謝和弦 D.C.WR-Chord 夠愛【歌詞】",artist:"謝和弦 ",src:"music/東城衛x謝和弦 D.C.WR-Chord 夠愛【歌詞】.mp3"},
{name:"0100. 金莎 - 愛的魔法-希望你就是對的人",artist:"金莎 ",src:"music/金莎 - 愛的魔法-希望你就是對的人.mp3"}
];
