trackList = 
[
{name:"0001. Bad Guy壞女人 ",artist:"Billie Eilish ",src:"music/Billie Eilish - Bad Guy壞女人中文字幕 Lyrics.mp3"},
{name:"0002. 宇宙最強神團 LSD 神曲 Audio (中字MV)",artist:" LSD ",src:"music/宇宙最強神團 LSD 神曲 Audio (中字MV).mp3"},
{name:"0003. Ariana Grande - Side to Side",artist:"Ariana Grande ",src:"music/Ariana Grande - Side to Side - Sexy Bike Riding Version.mp3"},
{name:"0004. Avril Lavigne - When Youre Gone",artist:"Avril Lavigne ",src:"music/Avril Lavigne - When Youre Gone (Officia Music Video).mp3"},
{name:"0005. Avril Lavigne 艾薇兒 . Complicated 複雜 中文字幕",artist:"Avril Lavigne 艾薇兒 ",src:"music/Avril Lavigne 艾薇兒 . Complicated 複雜 中文字幕.mp3"},
{name:"0006. Avril Lavigne 艾薇兒 . Head Above Water 不再沉淪 ",artist:"Avril Lavigne 艾薇兒 ",src:"music/Avril Lavigne 艾薇兒 . Head Above Water 不再沉淪 中文字幕(TaiwaneseChinese Sub).mp3"},
{name:"0007. Beauty And A Beat - Justin Bieber (Alex Goot, Kurt Schneider, and Chrissy Costanza Cover)",artist:"Alex Goot, Kurt Schneider, and Chrissy Costanza Cover ",src:"music/Beauty And A Beat - Justin Bieber (Alex Goot, Kurt Schneider, and Chrissy Costanza Cover).mp3"},
{name:"0008. Clean Bandit - Mama (feat. Ellie Goulding) [Official Video]",artist:"Clean Bandit ",src:"music/Clean Bandit - Mama (feat. Ellie Goulding) [Official Video].mp3"},
{name:"0009. Clean Bandit - Solo (feat. Demi Lovato) [Official Video]",artist:"Clean Bandit ",src:"music/Clean Bandit - Solo (feat. Demi Lovato) [Official Video].mp3"},
{name:"0010. Clean Bandit - Symphony (feat. Zara Larsson) [Official Video]",artist:"Clean Bandit ",src:"music/Clean Bandit - Symphony (feat. Zara Larsson) [Official Video].mp3"},
{name:"0011. Counting Stars - One Republic - w Chrissy Alex Goot",artist:"Counting Stars ",src:"music/Counting Stars - One Republic - w Chrissy Alex Goot.mp3"},
{name:"0012. Crazy Frog - Axel F (Official Video)",artist:"Crazy Frog ",src:"music/Crazy Frog - Axel F (Official Video).mp3"},
{name:"0013. Luis Fonsi - Despacito ft. Daddy Yankee",artist:"Luis Fonsi ",src:"music/Luis Fonsi - Despacito ft. Daddy Yankee.mp3"},
{name:"0014. PSY - ‘New Face’ MV",artist:"PSY ",src:"music/PSY - ‘New Face’ MV.mp3"},
{name:"0015. PSY - DADDY(feat. CL of 2NE1) MV",artist:"PSY ",src:"music/PSY - DADDY(feat. CL of 2NE1) MV.mp3"},
{name:"0016. Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song)",artist:"Shakira ",src:"music/Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song).mp3"},
{name:"0017. TONES AND I - DANCE MONKEY (OFFICIAL VIDEO)",artist:"TONES AND I  ",src:"music/TONES AND I - DANCE MONKEY (OFFICIAL VIDEO).mp3"},
{name:"0018. 宇宙最強神團 LSD 神曲 Audio (中字MV)",artist:"宇宙最強神團 LSD ",src:"music/宇宙最強神團 LSD 神曲 Audio (中字MV).mp3"},
{name:"0019. 老菸槍雙人組 The Chainsmokers ft. Halsey 海爾希 - 靠近我 Closer 中文字幕 MV",artist:"老菸槍雙人組 The Chainsmokers ",src:"music/老菸槍雙人組 The Chainsmokers ft. Halsey 海爾希 - 靠近我 Closer 中文字幕 MV.mp3"},
{name:"0020. 老菸槍雙人組 The Chainsmokers 期盼 Hope (中字MV)",artist:"老菸槍雙人組 ",src:"music/老菸槍雙人組 The Chainsmokers 期盼 Hope (中字MV).mp3"},
{name:"0021. 老菸槍雙人組與碧碧蕾克莎 The Chainsmokers Bebe Rexha 你是我的 Call You Mine (中字MV)",artist:"老菸槍雙人組 ",src:"music/老菸槍雙人組與碧碧蕾克莎 The Chainsmokers Bebe Rexha 你是我的 Call You Mine (中字MV).mp3"},
{name:"0022. Something Just Like This 如此而已 - The Chainsmokers Coldplay ",artist:"Something Just Like This ",src:"music/拯救了整座城市，卻救不了你：Something Just Like This 如此而已 - The Chainsmokers Coldplay 剪輯版 蜘蛛人驚奇再起 中文字幕.mp3"},
{name:"0023. 馬汀蓋瑞克斯 Martin Garrix 與 Bebe Rexha 以愛之名 In The Name Of Love (HD中字MV)",artist:"馬汀蓋瑞克斯 Martin Garrix ",src:"music/馬汀蓋瑞克斯 Martin Garrix 與 Bebe Rexha 以愛之名 In The Name Of Love (HD中字MV).mp3"},
{name:"0024. Q Park - AY AY AY (Official Music Video)",artist:"Q Park ",src:"music/Q Park - AY AY AY (Official Music Video).mp3"},
{name:"0025. Ava Max - So Am I [Official Music Video]",artist:"Ava Max ",src:"music/Ava Max - So Am I [Official Music Video].mp3"},
{name:"0026. Avril Lavigne - What The Hell (Official Music Video)",artist:"Avril Lavigne ",src:"music/Avril Lavigne - What The Hell (Official Music Video).mp3"},
{name:"0027. Avril Lavigne - Girlfriend (Official Music Video)",artist:"Avril Lavigne ",src:"music/Avril Lavigne - Girlfriend (Official Music Video).mp3"},
{name:"0028. 珍妮佛洛佩茲與馬盧瑪 Jennifer Lopez Maluma 只為你 Pa Ti (中字MV)",artist:"珍妮佛洛佩茲與馬盧瑪 ",src:"music/珍妮佛洛佩茲與馬盧瑪 Jennifer Lopez Maluma 只為你 Pa Ti (中字MV).mp3"},
{name:"0029. 黑眼豆豆與夏奇拉 Black Eyed Peas   Shakira 像我這樣的女孩 Girl Like Me (中字MV)",artist:"黑眼豆豆與夏奇拉 ",src:"music/黑眼豆豆與夏奇拉 Black Eyed Peas   Shakira 像我這樣的女孩 Girl Like Me (中字MV).mp3"},
{name:"0030. Maroon 5 - Animals (Lyrics)",artist:"Maroon 5 ",src:"music/Maroon 5 - Animals (Lyrics).mp3"},
{name:"0031. Clean Bandit 清潔的盜賊 - Rockabye 乖乖睡 feat. Sean Paul 尚保羅 Anne-Marie 安瑪莉 (華納 Official 高畫質 HD 官方完整版 MV)",artist:"Clean Bandit 清潔的盜賊  ",src:"music/Clean Bandit 清潔的盜賊 - Rockabye 乖乖睡 feat. Sean Paul 尚保羅 Anne-Marie 安瑪莉 (華納 Official 高畫質 HD 官方完整版 MV).mp3"},
{name:"0032. 老菸槍雙人組 The Chainsmokers 帶走愛 Takeaway (中字MV)",artist:"老菸槍雙人組 ",src:"music/老菸槍雙人組 The Chainsmokers 帶走愛 Takeaway (中字MV).mp3"},
{name:"0033. Ed Sheeran - Shape of You [Official Video]",artist:"Ed Sheeran ",src:"music/Ed Sheeran - Shape of You [Official Video].mp3"},
{name:"0034. Maroon 5 - Sugar (Lyrics)",artist:"馬輪壞 ",src:"music/Maroon 5 - Sugar (Lyrics).mp3"},
{name:"0035. Maroon 5 - Maps (Lyric Video)",artist:"馬輪壞 ",src:"music/Maroon 5 - Maps (Lyric Video).mp3"},
{name:"0036. PSY - GENTLEMAN MV",artist:"PSY ",src:"music/PSY - GENTLEMAN MV.mp3"},
{name:"0037. [Official Video] The Writers 寫手《灼火》 網路影集Mr.Bartender第三季片尾曲",artist:"Mr.Bartender ",src:"music/[Official Video] The Writers 寫手《灼火》 網路影集Mr.Bartender第三季片尾曲.mp3"},
{name:"0038. [Official Video] The Writers 寫手-剪一段我",artist:"寫手 ",src:"music/[Official Video] The Writers 寫手-剪一段我.mp3"},
{name:"0039. [音樂] 我管你 華晨宇",artist:"華晨宇 ",src:"music/[音樂] 我管你 華晨宇.mp3"},
{name:"0040. Ava Max - OMG Whats Happening [Official Music Video]",artist:"Ava Max ",src:"music/Ava Max - OMG Whats Happening [Official Music Video].mp3"},
{name:"0041. Charlie Puth - Attention [Official Video]",artist:"Charlie Puth ",src:"music/Charlie Puth - Attention [Official Video].mp3"},
{name:"0042. Clean Bandit and Mabel - Tick Tock (feat. 24kGoldn) [Official Video]",artist:"Clean Bandit ",src:"music/Clean Bandit and Mabel - Tick Tock (feat. 24kGoldn) [Official Video].mp3"},
{name:"0043. Clean Bandit 清潔的盜賊 - Mama feat. Ellie Goulding 艾麗高登 (華納 official HD 官方完整版 MV)",artist:"Clean Bandit ",src:"Clean Bandit 清潔的盜賊 - Mama feat. Ellie Goulding 艾麗高登 (華納 official HD 官方完整版 MV).mp3"},
{name:"0044. Diana Wang (王詩安) - HOME (Official Music Video)",artist:"王詩安 ",src:"music/Diana Wang (王詩安) - HOME (Official Music Video).mp3"},
{name:"0045. G.E.M.【來自天堂的魔鬼 AWAY】Official MV [HD] 鄧紫棋",artist:"鄧紫棋 ",src:"music/G.E.M.【來自天堂的魔鬼 AWAY】Official MV [HD] 鄧紫棋.mp3"},
{name:"0046. G.E.M.鄧紫棋【摩天動物園 City Zoo】Official Music Video",artist:"鄧紫棋 ",src:"music/G.E.M.鄧紫棋【摩天動物園 City Zoo】Official Music Video.mp3"},
{name:"0047. G.E.M-光年之外 LIGHT YEARS AWAY ",artist:"鄧紫棋",src:"music/G.E.M-光年之外 LIGHT YEARS AWAY .mp3"},
{name:"0048. G22 -【 蜜汁沼澤 】Official Music Video ( 韓力峻 KK 高爾宣 OSN 丁瑋 BT )",artist:"G22 ",src:"music/G22 -【 蜜汁沼澤 】Official Music Video ( 韓力峻 KK 高爾宣 OSN 丁瑋 BT ).mp3"},
{name:"0049. Jay Chou 周杰倫【稻香 Rice Field】-Official Music Video",artist:"周杰倫 ",src:"Jay Chou 周杰倫【稻香 Rice Field】-Official Music Video.mp3"},
{name:"0050. Mayday五月天[傷心的人別聽慢歌(貫徹快樂)]MV官方完整版-諾亞方舟3D電影主題曲",artist:"五月天 ",src:"music/Mayday五月天[傷心的人別聽慢歌(貫徹快樂)]MV官方完整版-諾亞方舟3D電影主題曲.mp3"},
{name:"0051. Mi2 - 勇敢愛",artist:"Mi2 ",src:"music/Mi2 - 勇敢愛.mp3"},
{name:"0052. Naughty Boy - La la la ft. Sam Smith (Official Video)",artist:"Naughty Boy ",src:"music/Naughty Boy - La la la ft. Sam Smith (Official Video).mp3"},
{name:"0053. Pharrell Williams - Happy (Official Music Video)",artist:"Pharrell Williams ",src:"music/Pharrell Williams - Happy (Official Music Video).mp3"},
{name:"0054. Rosie楊凱琳余楓《怎麼還不愛 Why Not Love》Official Music Video",artist:"楊凱琳余楓 ",src:"music/Rosie楊凱琳余楓《怎麼還不愛 Why Not Love》Official Music Video.mp3"},
{name:"0055. Shakira - Try Everything 全力以赴 中英文歌詞",artist:"Shakira ",src:"music/Shakira - Try Everything 全力以赴 中英文歌詞.mp3"},
{name:"0056. Shawn Mendes - Theres Nothing Holdin Me Back",artist:"Shawn Mendes ",src:"music/Shawn Mendes - Theres Nothing Holdin Me Back.mp3"},
{name:"0057. Shawn Mendes - Treat You Better",artist:"Shawn Mendes ",src:"music/Shawn Mendes - Treat You Better.mp3"},
{name:"0058. The Writers 寫手 [ BURN ]-網路影集《私室》主題曲",artist:"寫手 ",src:"music/The Writers 寫手 [ BURN ]-網路影集《私室》主題曲.mp3"},
{name:"0059. The Writers 寫手 《To My World》- Mr.Bartender主題曲",artist:"寫手 ",src:"music/The Writers 寫手 《To My World》- Mr.Bartender主題曲.mp3"},
{name:"0060. The Writers 寫手-自由歌",artist:"寫手 ",src:"music/The Writers 寫手-自由歌.mp3"},
{name:"0061. Tokyo Bon 東京盆踊り2020 (MakuDonarudo) Namewee 黃明志 ",artist:"黃明志 ",src:"music/Tokyo Bon 東京盆踊り2020 (MakuDonarudo) Namewee 黃明志 .mp3"},
{name:"0062. UNDER LOVER - 癡情玫瑰花 ft 玖壹壹 春風 (官方Music video)",artist:"UNDER LOVER ",src:"music/UNDER LOVER - 癡情玫瑰花 ft 玖壹壹 春風 (官方Music video).mp3"},
{name:"0063. VAVA - 我的新衣 My New Swag (Feat. Ty. 王倩倩) (華納 Official HD 官方MV)",artist:"VAVA ",src:"music/VAVA - 我的新衣 My New Swag (Feat. Ty. 王倩倩) (華納 Official HD 官方MV).mp3"},
{name:"0064. 蔡黃汝 - 迷人的危險",artist:"蔡黃汝 ",src:"music/0064. 蔡黃汝 - 迷人的危險.mp3"},
{name:"0065. 李千那 - 不敢聽的歌",artist:"李千那 ",src:"music/0065. 李千那 - 不敢聽的歌.mp3"},
{name:"0066. 徐若瑄 - 別人的 (電影孤味片尾曲)",artist:"徐若瑄 ",src:"music/0066. 徐若瑄 - 別人的 (電影孤味片尾曲).mp3"},
{name:"0067. G.E.M. 鄧紫棋 - Fly Away",artist:"G.E.M. 鄧紫棋 ",src:"music/0067. G.E.M. 鄧紫棋 - Fly Away.mp3"},
{name:"0068. 田馥甄 - 皆可",artist:"田馥甄 ",src:"music/0068. 田馥甄 - 皆可.mp3"},
{name:"0069. 任家萱 - 心如止水",artist:"任家萱 ",src:"music/0069. 任家萱 - 心如止水.mp3"},
{name:"0070. 滅火器 (Fire EX.) - 自信勇敢咱的名",artist:"滅火器 (Fire EX.) ",src:"music/0070. 滅火器 (Fire EX.) - 自信勇敢咱的名.mp3"},
{name:"0071. 鄭心慈 - 幸福藏在哪裡(天堂的微笑片頭曲)",artist:"鄭心慈 ",src:"music/0071. 鄭心慈 - 幸福藏在哪裡(天堂的微笑片頭曲).mp3"},
{name:"0072. 派偉俊 - Don’t Wanna Lie (feat. 8lak, Hosea)",artist:"派偉俊 ",src:"music/0072. 派偉俊 - Don’t Wanna Lie (feat. 8lak, Hosea).mp3"},
{name:"0073. 吳卓源 - Take Me Back",artist:"吳卓源 ",src:"music/0073. 吳卓源 - Take Me Back.mp3"},
{name:"0074. 田馥甄 - 無人知曉",artist:"田馥甄 ",src:"music/0074. 田馥甄 - 無人知曉.mp3"},
{name:"0075. 楊丞琳 - 像是一顆星星",artist:"楊丞琳 ",src:"music/0075. 楊丞琳 - 像是一顆星星.mp3"},
{name:"0076. TRASH - 希望你回來",artist:"TRASH ",src:"music/0076. TRASH - 希望你回來.mp3"},
{name:"0077. 陳忻玥 - 時間的輪",artist:"陳忻玥 ",src:"music/0077. 陳忻玥 - 時間的輪.mp3"},
{name:"0078. 吳卓源 - Things Things Things",artist:"吳卓源 ",src:"music/0078. 吳卓源 - Things Things Things.mp3"},
{name:"0079. 田馥甄 - 諷刺的情書",artist:"田馥甄 ",src:"music/0079. 田馥甄 - 諷刺的情書.mp3"},
{name:"0080. 陳忻玥  - Am I Who I Am",artist:"陳忻玥  ",src:"music/0080. 陳忻玥  - Am I Who I Am.mp3"},
{name:"0081. 李友廷 - 偽裝 (feat. 吳霏&楊碧琪)",artist:"李友廷 ",src:"music/0081. 李友廷 - 偽裝 (feat. 吳霏&楊碧琪).mp3"},
{name:"0082. 許光漢 - 別再想見我",artist:"許光漢 ",src:"music/0082. 許光漢 - 別再想見我.mp3"},
{name:"0083. 動力火車 - 永遠不再 (做工的人戲劇片尾曲)",artist:"動力火車 ",src:"music/0083. 動力火車 - 永遠不再 (做工的人戲劇片尾曲).mp3"},
{name:"0084. 李榮浩 - 等著等著就老了",artist:"李榮浩 ",src:"music/0084. 李榮浩 - 等著等著就老了.mp3"},
{name:"0085. 八三夭 - 有一種悲傷叫蠢蛋 (feat. A-Lin)",artist:"八三夭 ",src:"music/0085. 八三夭 - 有一種悲傷叫蠢蛋 (feat. A-Lin).mp3"},
{name:"0086. 老莫 ILL MO - 女士優先 (feat.壞特)",artist:"老莫 ILL MO ",src:"music/0086. 老莫 ILL MO - 女士優先 (feat.壞特).mp3"},
{name:"0087. 吳卓源 - Better (feat. 陳芳語)",artist:"吳卓源 ",src:"music/0087. 吳卓源 - Better (feat. 陳芳語).mp3"},
{name:"0088. IVAN 艾文 - Be Alright (feat. 李艾薇 Ivy Lee)",artist:"IVAN 艾文 ",src:"music/0088. IVAN 艾文 - Be Alright (feat. 李艾薇 Ivy Lee).mp3"},
{name:"0089. 楊丞琳 - 節日快樂",artist:"楊丞琳 ",src:"music/0089. 楊丞琳 - 節日快樂.mp3"},
{name:"0090. 茄子蛋 - 我的未來不是夢",artist:"茄子蛋 ",src:"music/0090. 茄子蛋 - 我的未來不是夢.mp3"},
{name:"0091. 梁文音 - 你存在",artist:"梁文音 ",src:"music/0091. 梁文音 - 你存在.mp3"},
{name:"0092. 采子 - 前任 (feat. 黃偉晉)",artist:"采子 ",src:"music/0092. 采子 - 前任 (feat. 黃偉晉).mp3"},
{name:"0093. 邱振哲 - 太陽 (堅持守護希望版)",artist:"邱振哲 ",src:"music/0093. 邱振哲 - 太陽 (堅持守護希望版).mp3"},
{name:"0094. 張語噥 - 不在乎",artist:"張語噥 ",src:"music/0094. 張語噥 - 不在乎.mp3"},
{name:"0095. 陳芳語 - 逆光",artist:"陳芳語 ",src:"music/0095. 陳芳語 - 逆光.mp3"},
{name:"0096. CHING G SQUAD, 高爾宣 OSN, 婁峻碩, ChrisFlow, RED芮德, Julia Wu, Karencici, Pi Hai Ryan - Better Than Love",artist:"CHING G SQUAD, 高爾宣 OSN, 婁峻碩, ChrisFlow, RED芮德, Julia Wu, Karencici, Pi Hai Ryan ",src:"music/0096. CHING G SQUAD, 高爾宣 OSN, 婁峻碩, ChrisFlow, RED芮德, Julia Wu, Karencici, Pi Hai Ryan - Better Than Love.mp3"},
{name:"0097. 韋禮安 - 雙棲動物",artist:"韋禮安 ",src:"music/0097. 韋禮安 - 雙棲動物.mp3"},
{name:"0098. 玖壹壹 - LOCAL",artist:"玖壹壹 ",src:"music/0098. 玖壹壹 - LOCAL.mp3"},
{name:"0099. 孫盛希 - 逃 (電視劇想見你插曲)",artist:"孫盛希 ",src:"music/0099. 孫盛希 - 逃 (電視劇想見你插曲).mp3"},
{name:"0100. 茄子蛋 - 恰似你的溫柔",artist:"茄子蛋 ",src:"music/0100. 茄子蛋 - 恰似你的溫柔.mp3"}
];
