trackList = 
[
{name:"0001. Bad Guy壞女人 ",artist:"Billie Eilish ",src:"music/Billie Eilish - Bad Guy壞女人中文字幕 Lyrics.mp3"},
{name:"0002. 宇宙最強神團 LSD 神曲 Audio (中字MV)",artist:" LSD ",src:"music/宇宙最強神團 LSD 神曲 Audio (中字MV).mp3"},
{name:"0003. Ariana Grande - Side to Side",artist:"Ariana Grande ",src:"music/Ariana Grande - Side to Side - Sexy Bike Riding Version.mp3"},
{name:"0004. Avril Lavigne - When Youre Gone",artist:"Avril Lavigne ",src:"music/Avril Lavigne - When Youre Gone (Officia Music Video).mp3"},
{name:"0005. Avril Lavigne 艾薇兒 . Complicated 複雜 中文字幕",artist:"Avril Lavigne 艾薇兒 ",src:"music/Avril Lavigne 艾薇兒 . Complicated 複雜 中文字幕.mp3"},
{name:"0006. Avril Lavigne 艾薇兒 . Head Above Water 不再沉淪 ",artist:"Avril Lavigne 艾薇兒 ",src:"music/Avril Lavigne 艾薇兒 . Head Above Water 不再沉淪 中文字幕(TaiwaneseChinese Sub).mp3"},
{name:"0007. Beauty And A Beat - Justin Bieber (Alex Goot, Kurt Schneider, and Chrissy Costanza Cover)",artist:"Alex Goot, Kurt Schneider, and Chrissy Costanza Cover ",src:"music/Beauty And A Beat - Justin Bieber (Alex Goot, Kurt Schneider, and Chrissy Costanza Cover).mp3"},
{name:"0008. Clean Bandit - Mama (feat. Ellie Goulding) [Official Video]",artist:"Clean Bandit ",src:"music/Clean Bandit - Mama (feat. Ellie Goulding) [Official Video].mp3"},
{name:"0009. Clean Bandit - Solo (feat. Demi Lovato) [Official Video]",artist:"Clean Bandit ",src:"music/Clean Bandit - Solo (feat. Demi Lovato) [Official Video].mp3"},
{name:"0010. Clean Bandit - Symphony (feat. Zara Larsson) [Official Video]",artist:"Clean Bandit ",src:"music/Clean Bandit - Symphony (feat. Zara Larsson) [Official Video].mp3"},
{name:"0011. Counting Stars - One Republic - w Chrissy Alex Goot",artist:"Counting Stars ",src:"music/Counting Stars - One Republic - w Chrissy Alex Goot.mp3"},
{name:"0012. Crazy Frog - Axel F (Official Video)",artist:"Crazy Frog ",src:"music/Crazy Frog - Axel F (Official Video).mp3"},
{name:"0013. Luis Fonsi - Despacito ft. Daddy Yankee",artist:"Luis Fonsi ",src:"music/Luis Fonsi - Despacito ft. Daddy Yankee.mp3"},
{name:"0014. PSY - ‘New Face’ MV",artist:"PSY ",src:"music/PSY - ‘New Face’ MV.mp3"},
{name:"0015. PSY - DADDY(feat. CL of 2NE1) MV",artist:"PSY ",src:"music/PSY - DADDY(feat. CL of 2NE1) MV.mp3"},
{name:"0016. Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song)",artist:"Shakira ",src:"music/Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song).mp3"},
{name:"0017. TONES AND I - DANCE MONKEY (OFFICIAL VIDEO)",artist:"TONES AND I  ",src:"music/TONES AND I - DANCE MONKEY (OFFICIAL VIDEO).mp3"},
{name:"0018. 宇宙最強神團 LSD 神曲 Audio (中字MV)",artist:"宇宙最強神團 LSD ",src:"music/宇宙最強神團 LSD 神曲 Audio (中字MV).mp3"},
{name:"0019. 老菸槍雙人組 The Chainsmokers ft. Halsey 海爾希 - 靠近我 Closer 中文字幕 MV",artist:"老菸槍雙人組 The Chainsmokers ",src:"music/老菸槍雙人組 The Chainsmokers ft. Halsey 海爾希 - 靠近我 Closer 中文字幕 MV.mp3"},
{name:"0020. 老菸槍雙人組 The Chainsmokers 期盼 Hope (中字MV)",artist:"老菸槍雙人組 ",src:"music/老菸槍雙人組 The Chainsmokers 期盼 Hope (中字MV).mp3"},
{name:"0021. 老菸槍雙人組與碧碧蕾克莎 The Chainsmokers Bebe Rexha 你是我的 Call You Mine (中字MV)",artist:"老菸槍雙人組 ",src:"music/老菸槍雙人組與碧碧蕾克莎 The Chainsmokers Bebe Rexha 你是我的 Call You Mine (中字MV).mp3"},
{name:"0022. Something Just Like This 如此而已 - The Chainsmokers Coldplay ",artist:"Something Just Like This ",src:"music/拯救了整座城市，卻救不了你：Something Just Like This 如此而已 - The Chainsmokers Coldplay 剪輯版 蜘蛛人驚奇再起 中文字幕.mp3"},
{name:"0023. 馬汀蓋瑞克斯 Martin Garrix 與 Bebe Rexha 以愛之名 In The Name Of Love (HD中字MV)",artist:"馬汀蓋瑞克斯 Martin Garrix ",src:"music/馬汀蓋瑞克斯 Martin Garrix 與 Bebe Rexha 以愛之名 In The Name Of Love (HD中字MV).mp3"},
{name:"0024. Q Park - AY AY AY (Official Music Video)",artist:"Q Park ",src:"music/Q Park - AY AY AY (Official Music Video).mp3"},
{name:"0025. Ava Max - So Am I [Official Music Video]",artist:"Ava Max ",src:"music/Ava Max - So Am I [Official Music Video].mp3"},
{name:"0026. Avril Lavigne - What The Hell (Official Music Video)",artist:"Avril Lavigne ",src:"music/Avril Lavigne - What The Hell (Official Music Video).mp3"},
{name:"0027. Avril Lavigne - Girlfriend (Official Music Video)",artist:"Avril Lavigne ",src:"music/Avril Lavigne - Girlfriend (Official Music Video).mp3"},
{name:"0028. 珍妮佛洛佩茲與馬盧瑪 Jennifer Lopez Maluma 只為你 Pa Ti (中字MV)",artist:"珍妮佛洛佩茲與馬盧瑪 ",src:"music/珍妮佛洛佩茲與馬盧瑪 Jennifer Lopez Maluma 只為你 Pa Ti (中字MV).mp3"},
{name:"0029. 黑眼豆豆與夏奇拉 Black Eyed Peas   Shakira 像我這樣的女孩 Girl Like Me (中字MV)",artist:"黑眼豆豆與夏奇拉 ",src:"music/黑眼豆豆與夏奇拉 Black Eyed Peas   Shakira 像我這樣的女孩 Girl Like Me (中字MV).mp3"},
{name:"0030. Maroon 5 - Animals (Lyrics)",artist:"Maroon 5 ",src:"music/Maroon 5 - Animals (Lyrics).mp3"},
{name:"0031. Clean Bandit 清潔的盜賊 - Rockabye 乖乖睡 feat. Sean Paul 尚保羅 Anne-Marie 安瑪莉 (華納 Official 高畫質 HD 官方完整版 MV)",artist:"Clean Bandit 清潔的盜賊  ",src:"music/Clean Bandit 清潔的盜賊 - Rockabye 乖乖睡 feat. Sean Paul 尚保羅 Anne-Marie 安瑪莉 (華納 Official 高畫質 HD 官方完整版 MV).mp3"},
{name:"0032. 老菸槍雙人組 The Chainsmokers 帶走愛 Takeaway (中字MV)",artist:"老菸槍雙人組 ",src:"music/老菸槍雙人組 The Chainsmokers 帶走愛 Takeaway (中字MV).mp3"},
{name:"0033. Ed Sheeran - Shape of You [Official Video]",artist:"Ed Sheeran ",src:"music/Ed Sheeran - Shape of You [Official Video].mp3"},
{name:"0034. Maroon 5 - Sugar (Lyrics)",artist:"馬輪壞 ",src:"music/Maroon 5 - Sugar (Lyrics).mp3"},
{name:"0035. Maroon 5 - Maps (Lyric Video)",artist:"馬輪壞 ",src:"music/Maroon 5 - Maps (Lyric Video).mp3"},
{name:"0036. PSY - GENTLEMAN MV",artist:"PSY ",src:"music/PSY - GENTLEMAN MV.mp3"},
{name:"0037. 田馥甄 - 懸日",artist:"田馥甄 ",src:"music/0037. 田馥甄 - 懸日.mp3"},
{name:"0038. 四堅情WOLF (邱鋒澤、陳零九、黃偉晉、賴晏駒) - 速食愛情",artist:"四堅情WOLF (邱鋒澤、陳零九、黃偉晉、賴晏駒) ",src:"music/0038. 四堅情WOLF (邱鋒澤、陳零九、黃偉晉、賴晏駒) - 速食愛情.mp3"},
{name:"0039. G.E.M. 鄧紫棋 - 好想好想妳",artist:"G.E.M. 鄧紫棋 ",src:"music/0039. G.E.M. 鄧紫棋 - 好想好想妳.mp3"},
{name:"0040. 瘦子E.SO - Something I Don't Need",artist:"瘦子E.SO ",src:"music/0040. 瘦子E.SO - Something I Don't Need.mp3"},
{name:"0041. 胡66 - 後來遇見他",artist:"胡66 ",src:"music/0041. 胡66 - 後來遇見他.mp3"},
{name:"0042. 王艷薇 - 離開我的依賴",artist:"王艷薇 ",src:"music/0042. 王艷薇 - 離開我的依賴.mp3"},
{name:"0043. 蕭敬騰 - 猴籠",artist:"蕭敬騰 ",src:"music/0043. 蕭敬騰 - 猴籠.mp3"},
{name:"0044. 陳零九 - 再也不要 (feat. 韋禮安)",artist:"陳零九 ",src:"music/0044. 陳零九 - 再也不要 (feat. 韋禮安).mp3"},
{name:"0045. 瘦子E.SO - I Wish I Was There",artist:"瘦子E.SO ",src:"music/0045. 瘦子E.SO - I Wish I Was There.mp3"},
{name:"0046. 八三夭 - 馬子狗 (feat. 玖壹壹)",artist:"八三夭 ",src:"music/0046. 八三夭 - 馬子狗 (feat. 玖壹壹).mp3"},
{name:"0047. 小宇-宋念宇 - 默念你",artist:"小宇",src:"music/0047. 小宇-宋念宇 - 默念你.mp3"},
{name:"0048. 瘦子E.SO - 伯父",artist:"瘦子E.SO ",src:"music/0048. 瘦子E.SO - 伯父.mp3"},
{name:"0049. J.Sheon - 輸情歌 (Ballad)",artist:"J.Sheon ",src:"music/0049. J.Sheon - 輸情歌 (Ballad).mp3"},
{name:"0050. 梁靜茹&艾怡良 - 飄洋過海來看你",artist:"梁靜茹&艾怡良 ",src:"music/0050. 梁靜茹&艾怡良 - 飄洋過海來看你.mp3"},
{name:"0051. 陳零九 - 看見妳的聲音 (電視劇想見你插曲)",artist:"陳零九 ",src:"music/0051. 陳零九 - 看見妳的聲音 (電視劇想見你插曲).mp3"},
{name:"0052. 吳卓源 - 七十億分之一加一 ((1  7(10^9)) + 1)(feat. 婁峻碩)",artist:"吳卓源 ",src:"music/0052. 吳卓源 - 七十億分之一加一 ((1  7(10^9)) + 1)(feat. 婁峻碩).mp3"},
{name:"0053. G.E.M. 鄧紫棋 - 依然睡公主",artist:"G.E.M. 鄧紫棋 ",src:"music/0053. G.E.M. 鄧紫棋 - 依然睡公主.mp3"},
{name:"0054. 華晨宇 - 好想愛這個世界啊",artist:"華晨宇 ",src:"music/0054. 華晨宇 - 好想愛這個世界啊.mp3"},
{name:"0055. 閻奕格 - 少了一件牛仔褲 - 三立華劇跟鯊魚接吻片尾曲",artist:"閻奕格 ",src:"music/0055. 閻奕格 - 少了一件牛仔褲 - 三立華劇跟鯊魚接吻片尾曲.mp3"},
{name:"0056. G.E.M. 鄧紫棋 - 差不多姑娘",artist:"G.E.M. 鄧紫棋 ",src:"music/0056. G.E.M. 鄧紫棋 - 差不多姑娘.mp3"},
{name:"0057. 黃宣 - 一天(電視劇《想見你》插曲)",artist:"黃宣 ",src:"music/0057. 黃宣 - 一天(電視劇《想見你》插曲).mp3"},
{name:"0058. 林俊傑 - 交換餘生",artist:"林俊傑 ",src:"music/0058. 林俊傑 - 交換餘生.mp3"},
{name:"0059. 瘦子E.SO - Don't Worry About Me",artist:"瘦子E.SO ",src:"music/0059. 瘦子E.SO - Don't Worry About Me.mp3"},
{name:"0060. 李佳歡 - 如果的事 (feat. 許維芳)",artist:"李佳歡 ",src:"music/0060. 李佳歡 - 如果的事 (feat. 許維芳).mp3"},
{name:"0061. 瘦子E.SO - Follow You",artist:"瘦子E.SO ",src:"music/0061. 瘦子E.SO - Follow You.mp3"},
{name:"0062. 楊丞琳 - 刪拾",artist:"楊丞琳 ",src:"music/0062. 楊丞琳 - 刪拾.mp3"},
{name:"0063. 文慧如 - 全放空 (feat. 鼓鼓 呂思緯)",artist:"文慧如 ",src:"music/0063. 文慧如 - 全放空 (feat. 鼓鼓 呂思緯).mp3"},
{name:"0064. 蔡黃汝 - 迷人的危險",artist:"蔡黃汝 ",src:"music/0064. 蔡黃汝 - 迷人的危險.mp3"},
{name:"0065. 李千那 - 不敢聽的歌",artist:"李千那 ",src:"music/0065. 李千那 - 不敢聽的歌.mp3"},
{name:"0066. 徐若瑄 - 別人的 (電影孤味片尾曲)",artist:"徐若瑄 ",src:"music/0066. 徐若瑄 - 別人的 (電影孤味片尾曲).mp3"},
{name:"0067. G.E.M. 鄧紫棋 - Fly Away",artist:"G.E.M. 鄧紫棋 ",src:"music/0067. G.E.M. 鄧紫棋 - Fly Away.mp3"},
{name:"0068. 田馥甄 - 皆可",artist:"田馥甄 ",src:"music/0068. 田馥甄 - 皆可.mp3"},
{name:"0069. 任家萱 - 心如止水",artist:"任家萱 ",src:"music/0069. 任家萱 - 心如止水.mp3"},
{name:"0070. 滅火器 (Fire EX.) - 自信勇敢咱的名",artist:"滅火器 (Fire EX.) ",src:"music/0070. 滅火器 (Fire EX.) - 自信勇敢咱的名.mp3"},
{name:"0071. 鄭心慈 - 幸福藏在哪裡(天堂的微笑片頭曲)",artist:"鄭心慈 ",src:"music/0071. 鄭心慈 - 幸福藏在哪裡(天堂的微笑片頭曲).mp3"},
{name:"0072. 派偉俊 - Don’t Wanna Lie (feat. 8lak, Hosea)",artist:"派偉俊 ",src:"music/0072. 派偉俊 - Don’t Wanna Lie (feat. 8lak, Hosea).mp3"},
{name:"0073. 吳卓源 - Take Me Back",artist:"吳卓源 ",src:"music/0073. 吳卓源 - Take Me Back.mp3"},
{name:"0074. 田馥甄 - 無人知曉",artist:"田馥甄 ",src:"music/0074. 田馥甄 - 無人知曉.mp3"},
{name:"0075. 楊丞琳 - 像是一顆星星",artist:"楊丞琳 ",src:"music/0075. 楊丞琳 - 像是一顆星星.mp3"},
{name:"0076. TRASH - 希望你回來",artist:"TRASH ",src:"music/0076. TRASH - 希望你回來.mp3"},
{name:"0077. 陳忻玥 - 時間的輪",artist:"陳忻玥 ",src:"music/0077. 陳忻玥 - 時間的輪.mp3"},
{name:"0078. 吳卓源 - Things Things Things",artist:"吳卓源 ",src:"music/0078. 吳卓源 - Things Things Things.mp3"},
{name:"0079. 田馥甄 - 諷刺的情書",artist:"田馥甄 ",src:"music/0079. 田馥甄 - 諷刺的情書.mp3"},
{name:"0080. 陳忻玥  - Am I Who I Am",artist:"陳忻玥  ",src:"music/0080. 陳忻玥  - Am I Who I Am.mp3"},
{name:"0081. 李友廷 - 偽裝 (feat. 吳霏&楊碧琪)",artist:"李友廷 ",src:"music/0081. 李友廷 - 偽裝 (feat. 吳霏&楊碧琪).mp3"},
{name:"0082. 許光漢 - 別再想見我",artist:"許光漢 ",src:"music/0082. 許光漢 - 別再想見我.mp3"},
{name:"0083. 動力火車 - 永遠不再 (做工的人戲劇片尾曲)",artist:"動力火車 ",src:"music/0083. 動力火車 - 永遠不再 (做工的人戲劇片尾曲).mp3"},
{name:"0084. 李榮浩 - 等著等著就老了",artist:"李榮浩 ",src:"music/0084. 李榮浩 - 等著等著就老了.mp3"},
{name:"0085. 八三夭 - 有一種悲傷叫蠢蛋 (feat. A-Lin)",artist:"八三夭 ",src:"music/0085. 八三夭 - 有一種悲傷叫蠢蛋 (feat. A-Lin).mp3"},
{name:"0086. 老莫 ILL MO - 女士優先 (feat.壞特)",artist:"老莫 ILL MO ",src:"music/0086. 老莫 ILL MO - 女士優先 (feat.壞特).mp3"},
{name:"0087. 吳卓源 - Better (feat. 陳芳語)",artist:"吳卓源 ",src:"music/0087. 吳卓源 - Better (feat. 陳芳語).mp3"},
{name:"0088. IVAN 艾文 - Be Alright (feat. 李艾薇 Ivy Lee)",artist:"IVAN 艾文 ",src:"music/0088. IVAN 艾文 - Be Alright (feat. 李艾薇 Ivy Lee).mp3"},
{name:"0089. 楊丞琳 - 節日快樂",artist:"楊丞琳 ",src:"music/0089. 楊丞琳 - 節日快樂.mp3"},
{name:"0090. 茄子蛋 - 我的未來不是夢",artist:"茄子蛋 ",src:"music/0090. 茄子蛋 - 我的未來不是夢.mp3"},
{name:"0091. 梁文音 - 你存在",artist:"梁文音 ",src:"music/0091. 梁文音 - 你存在.mp3"},
{name:"0092. 采子 - 前任 (feat. 黃偉晉)",artist:"采子 ",src:"music/0092. 采子 - 前任 (feat. 黃偉晉).mp3"},
{name:"0093. 邱振哲 - 太陽 (堅持守護希望版)",artist:"邱振哲 ",src:"music/0093. 邱振哲 - 太陽 (堅持守護希望版).mp3"},
{name:"0094. 張語噥 - 不在乎",artist:"張語噥 ",src:"music/0094. 張語噥 - 不在乎.mp3"},
{name:"0095. 陳芳語 - 逆光",artist:"陳芳語 ",src:"music/0095. 陳芳語 - 逆光.mp3"},
{name:"0096. CHING G SQUAD, 高爾宣 OSN, 婁峻碩, ChrisFlow, RED芮德, Julia Wu, Karencici, Pi Hai Ryan - Better Than Love",artist:"CHING G SQUAD, 高爾宣 OSN, 婁峻碩, ChrisFlow, RED芮德, Julia Wu, Karencici, Pi Hai Ryan ",src:"music/0096. CHING G SQUAD, 高爾宣 OSN, 婁峻碩, ChrisFlow, RED芮德, Julia Wu, Karencici, Pi Hai Ryan - Better Than Love.mp3"},
{name:"0097. 韋禮安 - 雙棲動物",artist:"韋禮安 ",src:"music/0097. 韋禮安 - 雙棲動物.mp3"},
{name:"0098. 玖壹壹 - LOCAL",artist:"玖壹壹 ",src:"music/0098. 玖壹壹 - LOCAL.mp3"},
{name:"0099. 孫盛希 - 逃 (電視劇想見你插曲)",artist:"孫盛希 ",src:"music/0099. 孫盛希 - 逃 (電視劇想見你插曲).mp3"},
{name:"0100. 茄子蛋 - 恰似你的溫柔",artist:"茄子蛋 ",src:"music/0100. 茄子蛋 - 恰似你的溫柔.mp3"}
];
